#!/usr/bin/env python3

# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Build a libcudart version-node shim for the CoreX/Iluvatar runtime.

CoreX ships a CUDA-10.2-compatible runtime, but its ``libcudart.so.10.2``
exports every symbol under the modern ``CUDART`` version node -- the node its
own PyTorch build asks for.  Wheels built against stock CUDA 10.2, notably
``cupy-cuda102`` (the tests build their cuBLAS reference through cupy), ask for
the same symbols under the older ``libcudart.so.10.2`` node and therefore
cannot even be loaded::

    ImportError: .../cupy_backends/cuda/api/runtime...so:
    undefined symbol: cudaDeviceCanAccessPeer, version libcudart.so.10.2

This script generates a drop-in ``libcudart.so.10.2`` that re-exports the real
CoreX runtime under BOTH nodes: every exported function becomes a weak
trampoline that jumps through a pointer an ELF constructor fills in with
``dlopen()``/``dlsym()`` from the real library.  Both the CoreX torch and stock
CUDA-10.2 wheels then resolve their symbols.

The output directory must come first on ``LD_LIBRARY_PATH`` (tools/set-env.sh
arranges that for the iluvatar vendor).

Usage::

    tools/make_cudart_shim.py --out .venv/lib/cudart-shim \\
        [--candidate /usr/local/corex-4.4.0/lib64/libcudart.so.10.2 ...]
"""

import argparse
import glob
import os
import shutil
import subprocess
import sys

# Searched for the real runtime when --candidate does not point at one already.
# The versioned corex dirs are globbed so a runner that only ships
# /usr/local/corex-4.x.y (no /usr/local/corex symlink) still works; the
# generated shim is what the pinned corex torch is built against.
DEFAULT_CANDIDATES = (
    "/usr/local/corex/lib64/libcudart.so.10.2",
    "/usr/local/corex/lib/libcudart.so.10.2",
    "/usr/local/corex-*/lib64/libcudart.so.10.2",
    "/usr/local/corex-*/lib/libcudart.so.10.2",
    "/usr/local/cuda-10.2/lib64/libcudart.so.10.2",
    "/usr/local/cuda-10.2/lib/libcudart.so.10.2",
)

# Name the wheels are looking for (their DT_NEEDED / version node), and the
# version node the stock CUDA-10.2 runtime exports.
NODE = "libcudart.so.10.2"


def parse_args(argv):
    parser = argparse.ArgumentParser(
        description="build a libcudart version-node shim for CoreX"
    )
    parser.add_argument("--out", required=True, help="directory to build the shim in")
    parser.add_argument(
        "--candidate",
        action="append",
        default=[],
        metavar="PATH",
        help="real libcudart to forward to; searched before the built-in "
        "defaults and embedded in the shim in the order given",
    )
    return parser.parse_args(argv)


def expand(paths):
    """Expand globs, drop duplicates and keep only files that exist."""
    found = []
    for path in paths:
        for hit in sorted(glob.glob(path)) or [path]:
            if os.path.isfile(hit) and hit not in found:
                found.append(hit)
    return found


def exported_functions(path):
    """Names of the functions `path` exports, with the version node stripped."""
    out = subprocess.run(
        ["readelf", "--dyn-syms", "-W", path],
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    names = set()
    for line in out.splitlines():
        parts = line.split()
        # Columns: Num: Value Size Type Bind Vis Ndx Name
        if len(parts) < 8 or parts[0].rstrip(":") == "Num":
            continue
        typ, bind, ndx, name = parts[3], parts[4], parts[6], parts[7]
        if typ != "FUNC" or bind not in ("GLOBAL", "WEAK") or ndx == "UND":
            continue
        names.add(name.split("@")[0])
    return sorted(names)


def write_trampolines(path, syms):
    """Emit one weak trampoline per symbol, exported under both nodes.

    `.weak` matters: the real runtime's strong definition has to win the
    dlsym() lookup in the constructor, otherwise the trampoline resolves back
    to itself and every call recurses until the stack is gone.
    `.note.GNU-stack` has to come last, after the code, or the labels are
    assembled into a non-allocated section and end up as ABS symbols.
    """
    lines = ["/* generated by tools/make_cudart_shim.py -- do not edit */", "\t.text"]
    for sym in syms:
        lines += [
            f"\t.weak\t{sym}_v_cudart",
            f"\t.weak\t{sym}_v_lcudart",
            f"\t.type\t{sym}_v_cudart, @function",
            f"\t.type\t{sym}_v_lcudart, @function",
            f"{sym}_v_cudart:",
            f"{sym}_v_lcudart:",
            f"\tjmp\t*p_{sym}(%rip)",
            f"\t.size\t{sym}_v_cudart, .-{sym}_v_cudart",
            f"\t.symver\t{sym}_v_cudart, {sym}@@CUDART",
            f"\t.symver\t{sym}_v_lcudart, {sym}@{NODE}",
        ]
    lines.append('\t.section\t.note.GNU-stack,"",@progbits')
    with open(path, "w") as fh:
        fh.write("\n".join(lines) + "\n")


def write_init(path, syms, candidates):
    """Emit the constructor that fills the trampoline slots from the runtime."""
    with open(path, "w") as fh:
        fh.write("/* generated by tools/make_cudart_shim.py -- do not edit */\n")
        fh.write("#include <dlfcn.h>\n#include <stdio.h>\n#include <stdlib.h>\n\n")
        fh.write("/* Absolute paths are required: this library is itself found as\n")
        fh.write(" * `libcudart.so.10.2` on LD_LIBRARY_PATH. */\n")
        fh.write("static const char *const kRuntimes[] = {\n")
        for candidate in candidates:
            fh.write(f'    "{candidate}",\n')
        fh.write("};\n\n")
        for sym in syms:
            fh.write(f'__attribute__((visibility("hidden"))) void *p_{sym};\n')
        fh.write("\nstatic const char *const kNames[] = {\n")
        for sym in syms:
            fh.write(f'    "{sym}",\n')
        fh.write("};\n\nstatic void **const kSlots[] = {\n")
        for sym in syms:
            fh.write(f"    &p_{sym},\n")
        fh.write("};\n\n")
        fh.write(
            "__attribute__((constructor)) static void "
            "flagblas_cudart_shim_init(void) {\n"
            "    static const size_t kNumSymbols = "
            "sizeof(kNames) / sizeof(*kNames);\n"
            "    static const size_t kNumRuntimes = "
            "sizeof(kRuntimes) / sizeof(*kRuntimes);\n"
            '    const char *want = getenv("FLAGBLAS_CUDART_REAL");\n'
            "    const char *loaded = NULL;\n"
            "    void *handle = NULL;\n"
            "    size_t i;\n"
            "\n"
            "    if (want != NULL && *want != '\\0') {\n"
            "        handle = dlopen(want, RTLD_NOW | RTLD_GLOBAL);\n"
            "        loaded = want;\n"
            "    } else {\n"
            "        for (i = 0; i < kNumRuntimes; i++) {\n"
            "            handle = dlopen(kRuntimes[i], RTLD_NOW | RTLD_GLOBAL);\n"
            "            if (handle != NULL) {\n"
            "                loaded = kRuntimes[i];\n"
            "                break;\n"
            "            }\n"
            "        }\n"
            "    }\n"
            "    if (handle == NULL) {\n"
            '        fprintf(stderr, "libcudart shim: cannot load a real'
            ' runtime (%s)\\n",\n'
            '                want != NULL ? want : "all candidates failed");\n'
            "        abort();\n"
            "    }\n"
            "    for (i = 0; i < kNumSymbols; i++) {\n"
            "        kSlots[i][0] = dlsym(handle, kNames[i]);\n"
            "        if (kSlots[i][0] == NULL) {\n"
            '            fprintf(stderr, "libcudart shim: %s is missing from'
            ' %s\\n",\n'
            "                    kNames[i], loaded);\n"
            "            abort();\n"
            "        }\n"
            "    }\n"
            '    if (getenv("FLAGBLAS_CUDART_SHIM_DEBUG") != NULL) {\n'
            '        fprintf(stderr, "libcudart shim: forwarding %zu symbols'
            ' via %s\\n",\n'
            "                kNumSymbols, loaded);\n"
            "    }\n"
            "}\n"
        )


def main(argv=None):
    args = parse_args(argv)
    for tool in ("gcc", "readelf"):
        if shutil.which(tool) is None:
            sys.exit(f"{tool} is required to build the libcudart shim")

    candidates = expand(args.candidate + list(DEFAULT_CANDIDATES))
    if not candidates:
        sys.exit(
            "no libcudart.so.10.2 found under /usr/local/corex* or "
            "/usr/local/cuda-10.2; pass --candidate <path>"
        )
    real = candidates[0]
    try:
        syms = exported_functions(real)
    except (OSError, subprocess.CalledProcessError) as exc:
        sys.exit(f"cannot read the symbols of {real}: {exc}")
    if not syms:
        sys.exit(f"no exported functions in {real}; not a CUDA runtime?")

    out = os.path.abspath(args.out)
    os.makedirs(out, exist_ok=True)
    write_trampolines(os.path.join(out, "tramp.S"), syms)
    write_init(os.path.join(out, "init.c"), syms, candidates)
    with open(os.path.join(out, "shim.map"), "w") as fh:
        fh.write(f"CUDART {{\n    global: *;\n}};\n{NODE} {{\n    global: *;\n}};\n")

    # The shim has to be reachable as `libcudart.so.10.2` (the DT_NEEDED string
    # of the stock wheels), but its SONAME must differ from the real library's:
    # with an identical SONAME the loader would treat the real runtime's
    # absolute-path dlopen() as "already loaded" and hand back the shim.
    cmd = [
        "gcc",
        "-shared",
        "-fPIC",
        "-O2",
        "-Wl,-soname,libcudart_flagblas_shim.so.1",
        "-Wl,--version-script=shim.map",
        "-o",
        NODE,
        "tramp.S",
        "init.c",
        "-ldl",
    ]
    subprocess.run(cmd, cwd=out, check=True)
    print(f"{os.path.join(out, NODE)}: {len(syms)} symbols forwarding to {real}")
    print("candidates: " + ", ".join(candidates))
    return 0


if __name__ == "__main__":
    sys.exit(main())
